import { NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { db } from '@/lib/db';
import { requireUser } from '@/lib/auth';
import { fail, HttpError } from '@/lib/http';
const createSchema=z.object({name:z.string().trim().min(2),email:z.string().trim().email(),password:z.string().min(8),role:z.enum(['STAFF','SUPER_ADMIN']).default('STAFF')});
const updateSchema=z.object({id:z.string().min(1),name:z.string().trim().min(2),email:z.string().trim().email(),role:z.enum(['STAFF','SUPER_ADMIN']),active:z.boolean(),password:z.string().min(8).optional().or(z.literal(''))});
async function adminOnly(){const u=await requireUser();if(u.role!=='SUPER_ADMIN')throw new HttpError('Only a Super Admin can manage users.',403);return u;}
export async function GET(){const u=await adminOnly();return NextResponse.json(await db.user.findMany({where:{businessId:u.businessId},select:{id:true,name:true,email:true,role:true,active:true,createdAt:true},orderBy:{createdAt:'asc'}}));}
export async function POST(req:Request){const u=await adminOnly();try{const b=createSchema.parse(await req.json());const passwordHash=await bcrypt.hash(b.password,12);const created=await db.user.create({data:{businessId:u.businessId,name:b.name,email:b.email.toLowerCase(),passwordHash,role:b.role}});await db.auditLog.create({data:{businessId:u.businessId,userId:u.id,action:'USER_CREATED',recordType:'USER',recordId:created.id}});return NextResponse.json({id:created.id,name:created.name,email:created.email,role:created.role,active:created.active},{status:201});}catch(e){if((e as {code?:string})?.code==='P2002')return NextResponse.json({error:'A user with this email already exists.'},{status:409});return fail(e);}}
export async function PATCH(req:Request){const u=await adminOnly();try{const b=updateSchema.parse(await req.json());if(b.id===u.id&&(!b.active||b.role!=='SUPER_ADMIN'))throw new HttpError('You cannot disable or demote your own Super Admin account.');const target=await db.user.findFirst({where:{id:b.id,businessId:u.businessId}});if(!target)throw new HttpError('User not found.',404);const data:{name:string;email:string;role:'STAFF'|'SUPER_ADMIN';active:boolean;passwordHash?:string}={name:b.name,email:b.email.toLowerCase(),role:b.role,active:b.active};if(b.password)data.passwordHash=await bcrypt.hash(b.passwordHash,12);const updated=await db.user.update({where:{id:b.id},data});await db.auditLog.create({data:{businessId:u.businessId,userId:u.id,action:'USER_UPDATED',recordType:'USER',recordId:updated.id}});return NextResponse.json({id:updated.id,name:updated.name,email:updated.email,role:updated.role,active:updated.active});}catch(e){if((e as {code?:string})?.code==='P2002')return NextResponse.json({error:'A user with this email already exists.'},{status:409});return fail(e);}}
export async function DELETE(req:Request){const u=await adminOnly();try{const id=new URL(req.url).searchParams.get('id');if(!id)throw new HttpError('User ID is required.');if(id===u.id)throw new HttpError('You cannot delete your own account.');const target=await db.user.findFirst({where:{id,businessId:u.businessId}});if(!target)throw new HttpError('User not found.',404);const sales=await db.sale.count({where:{staffId:id,businessId:u.businessId}});if(sales>0){await db.user.update({where:{id},data:{active:false}});await db.auditLog.create({data:{businessId:u.businessId,userId:u.id,action:'USER_DEACTIVATED',recordType:'USER',recordId:id,metadata:{reason:'User has sales history'}});return NextResponse.json({ok:true,deactivated:true,message:'This user has sales history, so the account was deactivated instead of permanently deleting historical records.'});}await db.user.delete({where:{id}});await db.auditLog.create({data:{businessId:u.businessId,userId:u.id,action:'USER_DELETED',recordType:'USER',recordId:id}});return NextResponse.json({ok:true,deleted:true});}catch(e){return fail(e);}}
